import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="border-b">
          <div className="max-w-6xl mx-auto px-6 h-14 flex items-center justify-between">
            <Link href="/" className="font-medium">Personal Museum</Link>
            <nav className="flex items-center gap-4 text-sm">
              <Link href="/" className="underline-offset-4 hover:underline">Gallery</Link>
              <Link href="/timeline" className="underline-offset-4 hover:underline">Timeline</Link>
              <Link href="/exhibits/new" className="underline-offset-4 hover:underline">Add</Link>
            </nav>
          </div>
        </header>
        <main className="max-w-6xl mx-auto px-6 py-6">
          {children}
        </main>
      </body>
    </html>
  )
}
